# Simple workflow for deploying static content to GitHub Pages.
name: Deploy Sphinx content to Pages.

on:
  # Runs on pushes targeting the default branch.
  push:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment.
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying.
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ’¾
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Install Python ğŸ
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.0'
          cache: 'pip' # caching pip dependencies
      
      - name: Install requirements ğŸ”¨
        working-directory: .
        run: pip install -r requirements-docs.txt
      
      - name: Sphinx make dirhtml ğŸŒ
        working-directory: ./docs
        run: make dirhtml
      
      - name: Upload artifact ğŸš€
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs/build/dirhtml'
      
      - name: Deploy to GitHub Pages ğŸ’»
        id: deployment
        uses: actions/deploy-pages@v4
